name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the site in the jekyll/builder container
      run: |
        docker run --rm \
          --volume="$PWD:/srv/jekyll" \
          -it jekyll/builder:latest \
          jekyll build

    - name: Install dependencies
      run: |
        npm install htmlhint -g
        npm install csslint -g

    - name: Test HTML
      run: |
        htmlhint .

    - name: Test CSS
      run: |
        csslint .
