name: Testar HTML e CSS

on:
  push:
    branches:
      - main

jobs:
  testar-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Instalar dependências
      run: |
        npm install htmlhint -g
        npm install csslint -g

    - name: Testar HTML
      run: |
        htmlhint .
        
    - name: Testar CSS
      run: |
        csslint .
